import React, { useState } from 'react';
import { CareerAnalysis, RecommendedRole } from '../types';
import { 
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell 
} from 'recharts';
import { 
  Briefcase, CheckCircle, XCircle, BookOpen, 
  Layers, ArrowRight, Download, RefreshCw, Loader2
} from 'lucide-react';

interface AnalysisDashboardProps {
  data: CareerAnalysis;
  onReset: () => void;
}

const AnalysisDashboard: React.FC<AnalysisDashboardProps> = ({ data, onReset }) => {
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  // Parse percentage string to number for chart
  const chartData = data.recommended_roles.map(r => ({
    name: r.role.split(' ').slice(0, 2).join(' '), // Shorten name for axis
    fullRole: r.role,
    fit: parseInt(r.fit_percentage.replace('%', '')) || 0
  }));

  const handleExportPDF = () => {
    setIsGeneratingPdf(true);
    const element = document.getElementById('analysis-dashboard');
    const html = document.documentElement;
    const isDark = html.classList.contains('dark');
    
    // Disable transitions for instant theme switch during capture
    const body = document.body;
    const originalTransition = body.style.transition;
    body.style.transition = 'none';

    // Force light mode for professional white-paper look
    if (isDark) {
      html.classList.remove('dark');
    }

    // Configuration for html2pdf
    const opt = {
      margin:       [0.3, 0.4], // inches
      filename:     'pathfinder-career-plan.pdf',
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { scale: 2, useCORS: true, letterRendering: true },
      jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' },
      pagebreak:    { mode: ['avoid-all', 'css', 'legacy'] }
    };

    // Small timeout to allow DOM to repaint in light mode before capturing
    setTimeout(() => {
        // Use the globally loaded html2pdf library
        // @ts-ignore
        if (window.html2pdf) {
            // @ts-ignore
            window.html2pdf().set(opt).from(element).save().then(() => {
                // Restore original theme and state
                if (isDark) {
                  html.classList.add('dark');
                }
                body.style.transition = originalTransition;
                setIsGeneratingPdf(false);
            }).catch((err: any) => {
                console.error("PDF Export failed:", err);
                setIsGeneratingPdf(false);
                // Fallback restoration in case of error
                if (isDark) {
                    html.classList.add('dark');
                }
                body.style.transition = originalTransition;
            });
        } else {
            console.error("html2pdf library not loaded");
            setIsGeneratingPdf(false);
            window.print(); // Fallback to browser print
        }
    }, 100);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-fade-in pb-20">
      
      {/* Header Actions - Hidden in PDF */}
      <div className="flex flex-col md:flex-row justify-between items-center bg-white dark:bg-slate-800 p-6 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-700 transition-colors" data-html2canvas-ignore>
        <div>
          <h1 className="text-2xl font-bold text-slate-800 dark:text-slate-100">Career Analysis Report</h1>
          <p className="text-slate-500 dark:text-slate-400">Generated by AI based on your profile</p>
        </div>
        <div className="flex gap-3 mt-4 md:mt-0">
          <button 
            onClick={onReset}
            disabled={isGeneratingPdf}
            className="flex items-center gap-2 px-4 py-2 text-slate-600 dark:text-slate-300 bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600 rounded-lg font-medium transition-colors disabled:opacity-50"
          >
            <RefreshCw className="w-4 h-4" />
            New Analysis
          </button>
          <button 
            onClick={handleExportPDF}
            disabled={isGeneratingPdf}
            className="flex items-center gap-2 px-4 py-2 text-white bg-indigo-600 hover:bg-indigo-700 dark:bg-indigo-600 dark:hover:bg-indigo-500 rounded-lg font-medium shadow-md shadow-indigo-100 dark:shadow-none transition-colors disabled:opacity-75 disabled:cursor-wait"
          >
            {isGeneratingPdf ? (
                <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
                <Download className="w-4 h-4" />
            )}
            {isGeneratingPdf ? "Generating PDF..." : "Export PDF"}
          </button>
        </div>
      </div>

      {/* Main Content Wrapper for PDF Generation */}
      <div id="analysis-dashboard" className="space-y-8 p-1 bg-slate-50 dark:bg-slate-900 transition-colors">
        
        {/* PDF Header - Visible only in PDF (handled by showing it here but usually this div is the capture target) */}
        {/* We can add a specialized header that is part of the captured area */}
        <div className="hidden pb-6 border-b border-slate-200 mb-6" style={{ display: isGeneratingPdf ? 'block' : 'none' }}>
            <div className="flex items-center gap-2 mb-2">
                <div className="p-1.5 bg-indigo-600 rounded">
                    <Briefcase className="h-4 w-4 text-white" />
                </div>
                <span className="text-lg font-bold text-slate-900">Pathfinder AI Analysis</span>
            </div>
            <p className="text-sm text-slate-500">Generated on {new Date().toLocaleDateString()}</p>
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
            
            {/* Left Column: Roles & Skills (2/3 width) */}
            <div className="lg:col-span-2 space-y-8">
            
            {/* Top Recommendations Chart */}
            <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl shadow-lg shadow-indigo-50/50 dark:shadow-none border border-slate-100 dark:border-slate-700 transition-colors avoid-break">
                <h3 className="text-lg font-bold text-slate-800 dark:text-slate-100 mb-6 flex items-center gap-2">
                <Briefcase className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
                Role Fit Analysis
                </h3>
                <div className="h-64 w-full">
                <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={chartData} layout="vertical" margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                    <XAxis type="number" domain={[0, 100]} hide />
                    <YAxis type="category" dataKey="name" width={120} tick={{fontSize: 12, fill: 'currentColor'}} className="text-slate-600 dark:text-slate-400" />
                    <Tooltip 
                        cursor={{fill: 'transparent'}}
                        contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 12px rgba(0,0,0,0.1)', backgroundColor: '#1e293b', color: '#f8fafc' }}
                        itemStyle={{ color: '#f8fafc' }}
                        labelStyle={{ color: '#cbd5e1' }}
                    />
                    <Bar dataKey="fit" radius={[0, 4, 4, 0]} barSize={20}>
                        {chartData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.fit > 80 ? '#4f46e5' : entry.fit > 50 ? '#818cf8' : '#cbd5e1'} />
                        ))}
                    </Bar>
                    </BarChart>
                </ResponsiveContainer>
                </div>
            </div>

            {/* Detailed Roles */}
            <div className="space-y-4">
                <h3 className="text-lg font-bold text-slate-800 dark:text-slate-100">Recommended Roles</h3>
                {data.recommended_roles.map((role, idx) => (
                <div key={idx} className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-100 dark:border-slate-700 shadow-sm hover:shadow-md transition-all avoid-break">
                    <div className="flex justify-between items-start mb-3">
                    <h4 className="text-xl font-bold text-slate-900 dark:text-white">{role.role}</h4>
                    <span className={`px-3 py-1 rounded-full text-sm font-bold ${
                        parseInt(role.fit_percentage) > 80 
                        ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400' 
                        : 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-400'
                    }`}>
                        {role.fit_percentage} Match
                    </span>
                    </div>
                    <p className="text-slate-600 dark:text-slate-300 leading-relaxed">{role.justification}</p>
                </div>
                ))}
            </div>

            {/* Learning Roadmap */}
            <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-700 transition-colors avoid-break">
                <h3 className="text-lg font-bold text-slate-800 dark:text-slate-100 mb-6 flex items-center gap-2">
                <BookOpen className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
                Strategic Learning Roadmap
                </h3>
                <div className="relative border-l-2 border-indigo-100 dark:border-indigo-900 ml-3 space-y-8 pl-8 py-2">
                {data.learning_roadmap.map((item, idx) => (
                    <div key={idx} className="relative avoid-break">
                    <span className="absolute -left-[41px] top-1 h-5 w-5 rounded-full border-4 border-white dark:border-slate-800 bg-indigo-600 dark:bg-indigo-500 shadow-sm"></span>
                    <div className="flex flex-col sm:flex-row sm:items-baseline gap-2 mb-1">
                        <span className="text-xs font-bold tracking-wider text-indigo-600 dark:text-indigo-300 uppercase bg-indigo-50 dark:bg-indigo-900/30 px-2 py-1 rounded">
                        {item.week}
                        </span>
                        <h5 className="font-bold text-slate-900 dark:text-white">{item.focus}</h5>
                    </div>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">{item.resources}</p>
                    </div>
                ))}
                </div>
            </div>

            </div>

            {/* Right Column: Skills & Projects (1/3 width) */}
            <div className="space-y-8">
            
            {/* Skill Gap Analysis */}
            <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-700 transition-colors avoid-break">
                <h3 className="text-lg font-bold text-slate-800 dark:text-slate-100 mb-4">Skill Analysis</h3>
                
                <div className="mb-6">
                <h4 className="text-xs font-bold text-green-700 dark:text-green-400 uppercase tracking-wider mb-3 flex items-center gap-1">
                    <CheckCircle className="w-3 h-3" /> You Have
                </h4>
                <div className="flex flex-wrap gap-2">
                    {data.current_skills.map((skill, i) => (
                    <span key={i} className="px-3 py-1 bg-slate-100 dark:bg-slate-700 text-slate-700 dark:text-slate-300 text-xs font-medium rounded-full border border-slate-200 dark:border-slate-600">
                        {skill}
                    </span>
                    ))}
                </div>
                </div>

                <div>
                <h4 className="text-xs font-bold text-rose-600 dark:text-rose-400 uppercase tracking-wider mb-3 flex items-center gap-1">
                    <XCircle className="w-3 h-3" /> Missing / To Improve
                </h4>
                <div className="flex flex-wrap gap-2">
                    {data.missing_skills.map((skill, i) => (
                    <span key={i} className="px-3 py-1 bg-rose-50 dark:bg-rose-900/30 text-rose-700 dark:text-rose-300 text-xs font-medium rounded-full border border-rose-100 dark:border-rose-800">
                        {skill}
                    </span>
                    ))}
                </div>
                </div>
            </div>

            {/* Portfolio Projects */}
            <div className="bg-gradient-to-br from-indigo-600 to-violet-700 dark:from-indigo-800 dark:to-violet-900 text-white p-6 rounded-2xl shadow-lg avoid-break">
                <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                <Layers className="w-5 h-5" />
                Build These Projects
                </h3>
                <ul className="space-y-4">
                {data.portfolio_projects.map((proj, i) => (
                    <li key={i} className="flex gap-3 items-start bg-white/10 p-3 rounded-lg border border-white/10 hover:bg-white/20 transition-colors">
                    <ArrowRight className="w-4 h-4 mt-1 flex-shrink-0 opacity-70" />
                    <span className="text-sm font-medium leading-snug">{proj}</span>
                    </li>
                ))}
                </ul>
            </div>

            {/* Resume Improvements */}
            <div className="bg-amber-50 dark:bg-amber-950/30 p-6 rounded-2xl border border-amber-100 dark:border-amber-800/50 avoid-break">
                <h3 className="text-lg font-bold text-amber-900 dark:text-amber-100 mb-4">Resume Quick Wins</h3>
                <ul className="space-y-3">
                {data.resume_improvements.map((imp, i) => (
                    <li key={i} className="text-sm text-amber-800 dark:text-amber-200 list-disc list-inside marker:text-amber-500 dark:marker:text-amber-700">
                    {imp}
                    </li>
                ))}
                </ul>
            </div>

            </div>
        </div>
      </div>
    </div>
  );
};

export default AnalysisDashboard;