import React, { useState } from 'react';
import { CareerAnalysis } from '../types';
import { 
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell 
} from 'recharts';
import { 
  Briefcase, CheckCircle, XCircle, BookOpen, 
  Layers, ArrowRight, Download, RefreshCw, Loader2 
} from 'lucide-react';
// @ts-ignore
import html2pdf from 'html2pdf.js';

interface AnalysisDashboardProps {
  data: CareerAnalysis;
  onReset: () => void;
}

const AnalysisDashboard: React.FC<AnalysisDashboardProps> = ({ data, onReset }) => {
  const [isExporting, setIsExporting] = useState(false);
  
  // Parse percentage string to number for chart
  const chartData = data.recommended_roles.map(r => ({
    name: r.role.split(' ').slice(0, 2).join(' '), // Shorten name for axis
    fullRole: r.role,
    fit: parseInt(r.fit_percentage.replace('%', '')) || 0
  }));

  const handleExportPDF = async () => {
    setIsExporting(true);
    const element = document.getElementById('report-content');
    const html = document.documentElement;
    const isDark = html.classList.contains('dark');
    
    // Temporarily force light mode for clean PDF output
    if (isDark) {
      html.classList.remove('dark');
    }

    const opt = {
      margin: [10, 10] as [number, number], // Top/Bottom margin
      filename: 'Pathfinder_Career_Roadmap.pdf',
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { 
        scale: 2, 
        useCORS: true, 
        logging: false,
        letterRendering: true
      },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
    };

    try {
      await html2pdf().set(opt).from(element).save();
    } catch (error) {
      console.error('PDF Export Failed:', error);
      // Fallback to browser print if library fails
      window.print();
    } finally {
      // Restore theme
      if (isDark) {
        html.classList.add('dark');
      }
      setIsExporting(false);
    }
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-fade-in pb-20">
      
      {/* Action Buttons (Excluded from PDF via ID selection) */}
      <div className="flex flex-col md:flex-row justify-end items-center gap-3 no-print">
        <button 
          onClick={onReset}
          disabled={isExporting}
          className="flex items-center gap-2 px-4 py-2 text-slate-600 dark:text-slate-300 bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600 rounded-lg font-medium transition-colors disabled:opacity-50"
        >
          <RefreshCw className="w-4 h-4" />
          New Analysis
        </button>
        <button 
          onClick={handleExportPDF}
          disabled={isExporting}
          className="flex items-center gap-2 px-4 py-2 text-white bg-indigo-600 hover:bg-indigo-700 dark:bg-indigo-600 dark:hover:bg-indigo-500 rounded-lg font-medium shadow-md shadow-indigo-100 dark:shadow-none transition-colors disabled:opacity-70 disabled:cursor-wait"
        >
          {isExporting ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <Download className="w-4 h-4" />
          )}
          {isExporting ? 'Generating PDF...' : 'Download PDF'}
        </button>
      </div>

      {/* Printable / Exportable Content Area */}
      <div id="report-content" className="space-y-8 p-1">
        
        {/* Report Header */}
        <div className="bg-white dark:bg-slate-800 p-8 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-700 transition-colors">
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 bg-indigo-600 rounded-lg">
              <Briefcase className="h-6 w-6 text-white" />
            </div>
            <h1 className="text-3xl font-bold text-slate-900 dark:text-white">Career Analysis Report</h1>
          </div>
          <p className="text-slate-500 dark:text-slate-400 text-lg">
            Personalized strategic roadmap generated by Pathfinder AI
          </p>
        </div>

        <div className="grid lg:grid-cols-3 gap-8">
          
          {/* Left Column: Roles & Skills (2/3 width) */}
          <div className="lg:col-span-2 space-y-8">
            
            {/* Top Recommendations Chart */}
            <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl shadow-lg shadow-indigo-50/50 dark:shadow-none border border-slate-100 dark:border-slate-700 transition-colors break-inside-avoid">
              <h3 className="text-lg font-bold text-slate-800 dark:text-slate-100 mb-6 flex items-center gap-2">
                <Briefcase className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
                Role Fit Analysis
              </h3>
              <div className="h-64 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={chartData} layout="vertical" margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                    <XAxis type="number" domain={[0, 100]} hide />
                    <YAxis type="category" dataKey="name" width={120} tick={{fontSize: 12, fill: '#64748b'}} className="text-slate-600 dark:text-slate-400" />
                    <Tooltip 
                      cursor={{fill: 'transparent'}}
                      contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 12px rgba(0,0,0,0.1)', backgroundColor: '#1e293b', color: '#f8fafc' }}
                      itemStyle={{ color: '#f8fafc' }}
                      labelStyle={{ color: '#cbd5e1' }}
                    />
                    <Bar dataKey="fit" radius={[0, 4, 4, 0]} barSize={20}>
                      {chartData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.fit > 80 ? '#4f46e5' : entry.fit > 50 ? '#818cf8' : '#cbd5e1'} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Detailed Roles */}
            <div className="space-y-4">
              <h3 className="text-lg font-bold text-slate-800 dark:text-slate-100">Recommended Roles</h3>
              {data.recommended_roles.map((role, idx) => (
                <div key={idx} className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-100 dark:border-slate-700 shadow-sm break-inside-avoid">
                  <div className="flex justify-between items-start mb-3">
                    <h4 className="text-xl font-bold text-slate-900 dark:text-white">{role.role}</h4>
                    <span className={`px-3 py-1 rounded-full text-sm font-bold ${
                      parseInt(role.fit_percentage) > 80 
                        ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400' 
                        : 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-400'
                    }`}>
                      {role.fit_percentage} Match
                    </span>
                  </div>
                  <p className="text-slate-600 dark:text-slate-300 leading-relaxed">{role.justification}</p>
                </div>
              ))}
            </div>

            {/* Learning Roadmap */}
            <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-700 transition-colors break-inside-avoid">
              <h3 className="text-lg font-bold text-slate-800 dark:text-slate-100 mb-6 flex items-center gap-2">
                <BookOpen className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
                Strategic Learning Roadmap
              </h3>
              <div className="relative border-l-2 border-indigo-100 dark:border-indigo-900 ml-3 space-y-8 pl-8 py-2">
                {data.learning_roadmap.map((item, idx) => (
                  <div key={idx} className="relative">
                    <span className="absolute -left-[41px] top-1 h-5 w-5 rounded-full border-4 border-white dark:border-slate-800 bg-indigo-600 dark:bg-indigo-500 shadow-sm"></span>
                    <div className="flex flex-col sm:flex-row sm:items-baseline gap-2 mb-1">
                      <span className="text-xs font-bold tracking-wider text-indigo-600 dark:text-indigo-300 uppercase bg-indigo-50 dark:bg-indigo-900/30 px-2 py-1 rounded">
                        {item.week}
                      </span>
                      <h5 className="font-bold text-slate-900 dark:text-white">{item.focus}</h5>
                    </div>
                    <p className="text-slate-600 dark:text-slate-400 text-sm">{item.resources}</p>
                  </div>
                ))}
              </div>
            </div>

          </div>

          {/* Right Column: Skills & Projects (1/3 width) */}
          <div className="space-y-8">
            
            {/* Skill Gap Analysis */}
            <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl shadow-sm border border-slate-100 dark:border-slate-700 transition-colors break-inside-avoid">
              <h3 className="text-lg font-bold text-slate-800 dark:text-slate-100 mb-4">Skill Analysis</h3>
              
              <div className="mb-6">
                <h4 className="text-xs font-bold text-green-700 dark:text-green-400 uppercase tracking-wider mb-3 flex items-center gap-1">
                  <CheckCircle className="w-3 h-3" /> You Have
                </h4>
                <div className="flex flex-wrap gap-2">
                  {data.current_skills.map((skill, i) => (
                    <span key={i} className="px-3 py-1 bg-slate-100 dark:bg-slate-700 text-slate-700 dark:text-slate-300 text-xs font-medium rounded-full border border-slate-200 dark:border-slate-600">
                      {skill}
                    </span>
                  ))}
                </div>
              </div>

              <div>
                <h4 className="text-xs font-bold text-rose-600 dark:text-rose-400 uppercase tracking-wider mb-3 flex items-center gap-1">
                  <XCircle className="w-3 h-3" /> Missing / To Improve
                </h4>
                <div className="flex flex-wrap gap-2">
                  {data.missing_skills.map((skill, i) => (
                    <span key={i} className="px-3 py-1 bg-rose-50 dark:bg-rose-900/30 text-rose-700 dark:text-rose-300 text-xs font-medium rounded-full border border-rose-100 dark:border-rose-800">
                      {skill}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Portfolio Projects */}
            <div className="bg-gradient-to-br from-indigo-600 to-violet-700 dark:from-indigo-800 dark:to-violet-900 text-white p-6 rounded-2xl shadow-lg break-inside-avoid">
              <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                <Layers className="w-5 h-5" />
                Build These Projects
              </h3>
              <ul className="space-y-4">
                {data.portfolio_projects.map((proj, i) => (
                  <li key={i} className="flex gap-3 items-start bg-white/10 p-3 rounded-lg border border-white/10 hover:bg-white/20 transition-colors">
                    <ArrowRight className="w-4 h-4 mt-1 flex-shrink-0 opacity-70" />
                    <span className="text-sm font-medium leading-snug">{proj}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Resume Improvements */}
            <div className="bg-amber-50 dark:bg-amber-950/30 p-6 rounded-2xl border border-amber-100 dark:border-amber-800/50 break-inside-avoid">
              <h3 className="text-lg font-bold text-amber-900 dark:text-amber-100 mb-4">Resume Quick Wins</h3>
              <ul className="space-y-3">
                {data.resume_improvements.map((imp, i) => (
                  <li key={i} className="text-sm text-amber-800 dark:text-amber-200 list-disc list-inside marker:text-amber-500 dark:marker:text-amber-700">
                    {imp}
                  </li>
                ))}
              </ul>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
};

export default AnalysisDashboard;